version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 0
    groups:
      maven-security-updates:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 0
    groups:
      github-actions-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
